### ISSUE TITLE
Add change settings telemetry message

### ISSUE THREAD

**Issue by waxzce** [makers-for-life/makair-telemetry#8]
We need to be able to add an immediate event (like alert) for change of settings, because right now the latency of the change of the settings is really weird

**Comment by Mefl** [comment]
The latency is due to air budget we have to respect on LoRa frequency (we cannot emit more than 1% of the time, except for life issue (this is why the alert are emitted without any latency).

If we reduce the latency, the overhead of the connection is too important and we cannot respect the air budget. Cc @hbs

**Comment by waxzce** [comment]
I speak about the latency between the F411 and the raspi here
